version: '3.8'

volumes:
  mongo_vol:

networks:
  mongo_net:
    driver: bridge

services:
  mongo_db:
    image: mongo:7.0.2-jammy
    networks:
     - mongo_net
    volumes:
     - mongo_vol:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd

  mongo_express:
    image: mongo-express:1.0.0-20-alpine3.18
    networks:
     - mongo_net
    depends_on:
     - mongo_db
    ports:
     - 0881:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongouser
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongopwd
      ME_CONFIG_BASICAUTH_USERNAME: mongouser
      ME_CONFIG_BASICAUTH_PASSWORD: mongopwd
      ME_CONFIG_MONGODB_URL: mongodb://mongouser:mongopwd@mongo_db:27017/